### PR TITLE
Changed scss colors for dark theme

### PR DESCRIPTION
**Pull request by dalmia007**
@IvanLudvig . I have changed the colors of the blog for dark theme. If there is any particular color that you want me to change let me know. Also for the formula images that you have in the posts you might want to attach them again as the text for them is black and the background is almost black now. You should probably get them in white colored text.

### CODE REVIEW

**Comment by IvanLudvig** [comment]
Good job. I like the dark theme. I'm going to change my formulas and switch to the dark theme.
I really appreciate your efforts!

**Comment by dalmia007** [comment]
I am glad you liked it. Do let me know if something needs to be changed.I would be happy to have a look at it.

**Comment by dalmia007** [comment]
Also it would be great if you could merge it if everything is fine.

**Comment by IvanLudvig** [comment]
Of course. I will make edits to the formulas and then merge

**Pull request merged**
